/**
 * Blue whale hero art for the chat window — the OFFICIAL DeepSeek mark,
 * derived rather than redrawn.
 *
 * The brand mark is a single closed cubic-Bézier silhouette (see
 * `./whale-art.ts`, generated by `scripts/whale-gen.ts` from the official
 * `FishLogo` path). The previous art was a hand-drawn 16×24 grid ported from
 * another TUI — an approximation that never quite matched the mark. Rasterising
 * the real path means the TUI whale tracks the official one, and re-derives at
 * any width instead of needing a redraw per resolution.
 *
 * Rendering stays exactly as before: half-block glyphs (▀/▄/█) with one
 * highlight group per cell colour pair, so the nvim extmark pass colours each
 * glyph with foreground/background (truecolor + 256-colour).
 *
 * TUI-exclusive extras on top of the base silhouette: rising bubbles (spout)
 * and a rigid bob — the animation the web canvas does not do.
 */
import { type WhaleArtRow } from './whale-art.js';
export interface WhaleRenderRow {
    text: string;
    spans: Array<{
        s: number;
        e: number;
        group: string;
    }>;
}
/** Art tiers by column width, ascending. */
export declare const WHALE_TIERS: ReadonlyArray<{
    cols: number;
    rows: WhaleArtRow[];
}>;
/** Default (narrowest) tier — kept as the historical export shape. */
export declare const WHALE_RENDER_ROWS: WhaleRenderRow[];
/** Text rows of the default tier (the art is 9 rows at 24 columns). */
export declare const WHALE_ROWS: number;
/**
 * Widest tier that fits `width`, or null when the window is too narrow.
 * Wider tiers are strictly better here: the silhouette is a curve, so more
 * columns is more of the real outline rather than a stretched copy.
 */
export declare function pickWhaleTier(width: number): {
    cols: number;
    rows: WhaleRenderRow[];
} | null;
/**
 * Horizontally centre the whale in `width` (no vertical padding — the caller
 * composes the whole empty-state block and centres it as one unit).
 */
export declare function whaleRowsIndented(width: number, rows?: WhaleRenderRow[]): WhaleRenderRow[] | null;
/** Layout maths for the hero block. Called from the smoke suite (layout
 *  contract) — the feed's own hero path sizes itself. */
export declare function layoutWhaleRows(height: number, width: number, rows?: WhaleRenderRow[]): WhaleRenderRow[] | null;
/**
 * Animation frames. Pass the window width to animate at the tier the hero will
 * actually render, so the bob moves one real pixel (a 24-column bob applied to
 * the 48-column art would jump two).
 */
export declare function whaleFrames(width?: number): WhaleRenderRow[][];
/** Row count of the tallest (widest) tier — the hero's vertical budget. */
export declare const WHALE_MAX_ROWS: number;
/**
 * Watermark animation: the terminal's own emoji font renders the whale
 * (2 cells wide), so frames cycle the spouting whale ↔ plain whale — the
 * spout appears to pulse. No highlight groups: emoji carry their colors.
 */
export declare const WHALE_EMOJI_FRAMES: readonly string[];
