/**
 * Blue whale hero art for the chat window — the OFFICIAL DeepSeek mark,
 * derived rather than redrawn.
 *
 * The brand mark is a single closed cubic-Bézier silhouette (see
 * `./whale-art.ts`, generated by `scripts/whale-gen.ts` from the official
 * `FishLogo` path). The previous art was a hand-drawn 16×24 grid ported from
 * another TUI — an approximation that never quite matched the mark. Rasterising
 * the real path means the TUI whale tracks the official one, and re-derives at
 * any width instead of needing a redraw per resolution.
 *
 * Rendering stays exactly as before: half-block glyphs (▀/▄/█) with one
 * highlight group per cell colour pair, so the nvim extmark pass colours each
 * glyph with foreground/background (truecolor + 256-colour).
 *
 * TUI-exclusive extras on top of the base silhouette: rising bubbles (spout)
 * and a rigid bob — the animation the web canvas does not do.
 */

import { WHALE_24, WHALE_32, WHALE_48, WHALE_TIER_WIDTHS, type WhaleArtRow } from './whale-art.js'

export interface WhaleRenderRow {
  text: string
  spans: Array<{ s: number; e: number; group: string }>
}

/** Art tiers by column width, ascending. */
export const WHALE_TIERS: ReadonlyArray<{ cols: number; rows: WhaleArtRow[] }> = [
  { cols: 24, rows: WHALE_24 },
  { cols: 32, rows: WHALE_32 },
  { cols: 48, rows: WHALE_48 },
]

/** Narrowest window that still gets art (the 24-column tier + breathing room). */
const MIN_WIDTH = WHALE_TIER_WIDTHS[0]! + 16

/** Default (narrowest) tier — kept as the historical export shape. */
export const WHALE_RENDER_ROWS: WhaleRenderRow[] = toRenderRows(WHALE_24)
/** Text rows of the default tier (the art is 9 rows at 24 columns). */
export const WHALE_ROWS = WHALE_24.length

function toRenderRows(rows: WhaleArtRow[]): WhaleRenderRow[] {
  return rows.map((r) => ({
    text: r.t,
    spans: r.s.map((sp) => ({ s: sp.s, e: sp.e, group: `DshTuiWhale${sp.g}` })),
  }))
}

/**
 * Widest tier that fits `width`, or null when the window is too narrow.
 * Wider tiers are strictly better here: the silhouette is a curve, so more
 * columns is more of the real outline rather than a stretched copy.
 */
export function pickWhaleTier(width: number): { cols: number; rows: WhaleRenderRow[] } | null {
  if (width < MIN_WIDTH) return null
  let best: { cols: number; rows: WhaleRenderRow[] } | null = null
  for (const tier of WHALE_TIERS) {
    if (tier.cols <= width - 8) best = { cols: tier.cols, rows: toRenderRows(tier.rows) }
  }
  return best
}

/**
 * Horizontally centre the whale in `width` (no vertical padding — the caller
 * composes the whole empty-state block and centres it as one unit).
 */
export function whaleRowsIndented(width: number, rows: WhaleRenderRow[] = WHALE_RENDER_ROWS): WhaleRenderRow[] | null {
  if (width < MIN_WIDTH) return null
  const artWidth = rows[0]?.text.length ?? 0
  const indent = Math.max(0, Math.floor((width - artWidth) / 2))
  const pad = ' '.repeat(indent)
  return rows.map((r) => ({
    text: pad + r.text,
    spans: r.spans.map((sp) => ({ s: sp.s + indent, e: sp.e + indent, group: sp.group })),
  }))
}

/** Layout maths for the hero block. Called from the smoke suite (layout
 *  contract) — the feed's own hero path sizes itself. */
export function layoutWhaleRows(height: number, width: number, rows: WhaleRenderRow[] = WHALE_RENDER_ROWS): WhaleRenderRow[] | null {
  if (height < rows.length + 2) return null
  const indented = whaleRowsIndented(width, rows)
  if (indented === null) return null
  const topPad = Math.max(0, Math.floor((height - rows.length) / 2))
  const out: WhaleRenderRow[] = []
  for (let i = 0; i < topPad; i++) out.push({ text: '', spans: [] })
  return [...out, ...indented]
}

// ---------------------------------------------------------------------------
// Animation — 4 frames: bubble rises, and the whale bobs on the closing pair.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Animation — 4 frames: a bubble rises, and the whale bobs on the closing pair.
//
// Everything happens on a PIXEL BITMAP (rows of booleans, 2 rows per text row)
// rather than on the encoded spans: the encoded form is byte-offset based, so
// shifting or stamping pixels there means re-deriving indices (and the first
// cut of this got that wrong). A bitmap makes the transform trivial and the
// re-encode does the arithmetic once.
// ---------------------------------------------------------------------------

/** Decode a tier's rows into a pixel bitmap: true = body.
 *
 *  Two pixel rows per text row (that is what a half-block glyph encodes), so
 *  the bitmap is 2 × rows tall. Allocating only `rows.length` here silently
 *  dropped the lower half of every glyph and clipped the art to 6 of 9 rows. */
function rowsToBitmap(rows: WhaleArtRow[], cols: number): boolean[][] {
  const bits: boolean[][] = []
  // One extra pixel row of clearance at the BOTTOM: the bob shifts everything
  // down, and with no spare row that shift drops the art's lowest pixel row —
  // which is real silhouette (the belly), so the whale visibly lost mass on the
  // bob frames instead of moving. Painting the bitmap on transparent space is
  // also what the base art already assumes.
  for (let i = 0; i < rows.length * 2 + 1; i++) bits.push(new Array<boolean>(cols).fill(false))
  for (let c = 0; c < rows.length; c++) {
    const row = rows[c]!
    for (const sp of row.s) {
      // Walk the glyph run once, mirroring the encoder: leading spaces are one
      // byte each, every glyph is three, so a byte offset maps to a char index.
      let byte = 0
      let ch = 0
      for (const g of row.t) {
        if (byte >= sp.s && byte < sp.e) {
          const top = g === '█' || g === '▀'
          const bottom = g === '█' || g === '▄'
          if (top) bits[c * 2]![ch] = true
          if (bottom) bits[c * 2 + 1]![ch] = true
        }
        byte += Buffer.byteLength(g)
        ch++
      }
    }
  }
  return bits
}

/** Shift the whole silhouette one pixel row down (rigid; no row aliasing). */
function shiftDown(bits: boolean[][]): boolean[][] {
  const cols = bits[0]?.length ?? 0
  const out: boolean[][] = [new Array<boolean>(cols).fill(false)]
  for (let i = 0; i < bits.length - 1; i++) out.push([...(bits[i] ?? [])])
  return out
}

/** Shift one pixel row up. The bitmap carries a bottom clearance row (see
 *  rowsToBitmap), so this reintroduces no cropping from the other side. */
function shiftUp(bits: boolean[][]): boolean[][] {
  const cols = bits[0]?.length ?? 0
  const out: boolean[][] = []
  for (let i = 1; i < bits.length; i++) out.push([...(bits[i] ?? [])])
  out.push(new Array<boolean>(cols).fill(false))
  return out
}

/** Stamp one lit pixel (the rising bubble — TUI-exclusive spout). */
function withPixel(bits: boolean[][], row: number, col: number): boolean[][] {
  const out = bits.map((r) => [...r])
  const line = out[row]
  if (line !== undefined && col >= 0 && col < line.length) line[col] = true
  return out
}

/** Pixel bitmap → render rows (half-block encode + byte-offset spans). */
function bitmapToRows(bits: boolean[][], cols: number): WhaleRenderRow[] {
  const rows: WhaleRenderRow[] = []
  for (let c = 0; c * 2 + 1 < bits.length; c++) {
    const top = bits[c * 2] ?? []
    const bottom = bits[c * 2 + 1] ?? []
    let text = ''
    const spans: WhaleRenderRow['spans'] = []
    for (let x = 0; x < cols; x++) {
      const t = top[x] === true
      const b = bottom[x] === true
      if (!t && !b) { text += ' '; continue }
      const glyph = t && b ? '█' : t ? '▀' : '▄'
      const group = t && b ? 'DshTuiWhaleBB' : t ? 'DshTuiWhaleB-' : 'DshTuiWhale-B'
      const s = Buffer.byteLength(text)
      text += glyph
      spans.push({ s, e: Buffer.byteLength(text), group })
    }
    const trimmed = text.replace(/\s+$/, '')
    const cut = Buffer.byteLength(trimmed)
    rows.push({ text: trimmed, spans: spans.filter((sp) => sp.s < cut) })
  }
  return rows
}

/**
 * The 4 frames for one tier: a breathing bob (rest → down → up → rest), all
 * derived from ONE silhouette.
 *
 * A symmetric up/down pair keeps all four poses distinct at EVERY tier. An
 * earlier ordering bobbed only downward, which made two of the four frames
 * identical (and on the narrow tier, where the spout is suppressed, collapsed
 * the whole cycle to two poses).
 */
function frameBitmaps(rows: WhaleArtRow[], cols: number): boolean[][][] {
  const base = rowsToBitmap(rows, cols)
  const bubbleCol = cols >= 32 ? Math.round(cols * 0.42) : -1
  const spout = (bits: boolean[][]): boolean[][] =>
    bubbleCol >= 0 ? withPixel(bits, 0, bubbleCol) : bits
  // Ordered for a SEAMLESS loop: frame 3 (rest) is adjacent to frame 0 (up),
  // so the cycle reads up → rest → down → rest → up … The neighbouring frames
  // are what the feed actually shows back-to-back; repeating the rest pose is
  // correct for a breathing bob, and at every tier frames 0/1 and 1/2 differ.
  return [shiftUp(base), base, spout(shiftDown(base)), base]
}

/**
 * Animation frames. Pass the window width to animate at the tier the hero will
 * actually render, so the bob moves one real pixel (a 24-column bob applied to
 * the 48-column art would jump two).
 */
export function whaleFrames(width?: number): WhaleRenderRow[][] {
  const tier = width === undefined ? undefined : pickWhaleTier(width)
  if (tier === null) return [WHALE_RENDER_ROWS]
  const cols = tier?.cols ?? WHALE_TIER_WIDTHS[0]!
  const rows = tier === undefined ? WHALE_24 : WHALE_TIERS.find((t) => t.cols === cols)!.rows
  return frameBitmaps(rows, cols).map((b) => bitmapToRows(b, cols))
}

/** Row count of the tallest (widest) tier — the hero's vertical budget. */
export const WHALE_MAX_ROWS = Math.max(...WHALE_TIERS.map((t) => t.rows.length))

/**
 * Watermark animation: the terminal's own emoji font renders the whale
 * (2 cells wide), so frames cycle the spouting whale ↔ plain whale — the
 * spout appears to pulse. No highlight groups: emoji carry their colors.
 */
export const WHALE_EMOJI_FRAMES: readonly string[] = ['🐳', '🫧🐳']
